// Publishes the generated {table}/{state}/{code}.json files to the Cloudflare
// R2 bucket served at https://ibpt.nfe.io (bucket "ibpt", custom domain).
//
// usage: node publish-r2.js [--tables lc116,nbs,ncm] [--apply] [--no-delete]
//                           [--concurrency 32] [--allow-mass-delete]
//
//   default      dry-run: lists what would be uploaded and deleted, changes nothing
//   --apply      uploads and deletes for real
//   --tables     tables to publish (default: ncm,nbs,lc116)
//   --no-delete  keeps remote files that no longer exist locally
//
// Hand-made lc116 codes (nbs null in lc116-nbs-map.json) are never deleted.
//
// Requires R2_ACCOUNT_ID, R2_ACCESS_KEY_ID and R2_SECRET_ACCESS_KEY (an R2 API
// token with write access to the bucket), optionally R2_BUCKET (default: ibpt).
// Reads a .env file when present.
//
// Files are stored gzip compressed (Content-Encoding: gzip), the same way the
// bucket was migrated from Azure. Only files whose gzip content changed are
// uploaded. Only keys under the selected table prefixes are ever touched: other
// prefixes of the bucket (ex: data/) are never listed, uploaded or deleted.

var fs = require("fs");
var path = require("path");
var zlib = require("zlib");
var crypto = require("crypto");
var ibpt = require("./lib/ibpt");

// a table losing more than this share of its remote files needs --allow-mass-delete
var MASS_DELETE_RATIO = 0.25;

// only files generated by the generator are compared and deleted
var isTableKey = function (table, key) {
  var parts = key.split("/");
  return parts.length === 3 && parts[0] === table && /^[a-z]{2}$/.test(parts[1]) &&
    /^[^/]+\.json$/.test(parts[2]);
};

// lc116 codes without nbs in lc116-nbs-map.json are hand-made files that may exist
// only in the bucket (ex: lc116/rj/9999.json), so they are never deleted
var lc116NbsMap = JSON.parse(fs.readFileSync(path.join(__dirname, "lc116-nbs-map.json"), "utf8"));

var isManualKey = function (table, key) {
  var code = path.basename(key, ".json");
  return table === "lc116" && code !== "_comment" && lc116NbsMap[code] && !lc116NbsMap[code].nbs;
};

// local files of a table, keyed by their bucket key
var localFiles = function (table) {
  var files = {};

  ibpt.states.forEach(function (state) {
    var dir = path.join(table, state);
    if (!fs.existsSync(dir)) return;

    fs.readdirSync(dir).forEach(function (file) {
      if (path.extname(file) !== ".json") return;
      files[table + "/" + state + "/" + file] = path.join(dir, file);
    });
  });

  return files;
};

var gzipFile = function (file) {
  // gzipSync writes mtime 0 in the header, so the output (and the md5 used as
  // R2 etag) only changes when the content changes
  var body = zlib.gzipSync(fs.readFileSync(file), { level: 9 });
  return { body: body, md5: crypto.createHash("md5").update(body).digest("hex") };
};

// compares local and remote files of a table: { upload: [key], delete: [key], unchanged }
var plan = function (table, local, remote) {
  var result = { table: table, upload: [], delete: [], unchanged: 0, remoteCount: 0 };

  var keys = Object.keys(local);

  keys.forEach(function (key, index) {
    if (index && index % 20000 === 0) console.log("  " + table + ": compared " + index + "/" + keys.length + " local files...");
    var md5 = gzipFile(local[key]).md5;
    if (remote[key] === md5) {
      result.unchanged++;
    } else {
      result.upload.push(key);
    }
  });

  Object.keys(remote).forEach(function (key) {
    if (!isTableKey(table, key)) return;
    result.remoteCount++;
    if (!local[key] && !isManualKey(table, key)) result.delete.push(key);
  });

  return result;
};

var createClient = function () {
  var S3Client = require("@aws-sdk/client-s3").S3Client;
  var missing = ["R2_ACCOUNT_ID", "R2_ACCESS_KEY_ID", "R2_SECRET_ACCESS_KEY"].filter(function (name) {
    return !process.env[name];
  });

  if (missing.length) {
    throw new Error("missing environment variables: " + missing.join(", "));
  }

  return new S3Client({
    region: "auto",
    endpoint: "https://" + process.env.R2_ACCOUNT_ID + ".r2.cloudflarestorage.com",
    credentials: {
      accessKeyId: process.env.R2_ACCESS_KEY_ID,
      secretAccessKey: process.env.R2_SECRET_ACCESS_KEY
    }
  });
};

// remote files under the table prefix: { key: etag }
var listRemote = async function (client, bucket, table) {
  var ListObjectsV2Command = require("@aws-sdk/client-s3").ListObjectsV2Command;
  var remote = {};
  var token;
  var pages = 0;

  do {
    var page = await client.send(new ListObjectsV2Command({
      Bucket: bucket,
      Prefix: table + "/",
      ContinuationToken: token
    }));

    (page.Contents || []).forEach(function (object) {
      remote[object.Key] = (object.ETag || "").replace(/"/g, "");
    });

    token = page.IsTruncated ? page.NextContinuationToken : null;
    if (++pages % 50 === 0) console.log("  " + table + ": listed " + Object.keys(remote).length + " remote files...");
  } while (token);

  return remote;
};

// runs fn over items with at most `concurrency` calls in flight, collecting failures
var eachLimit = async function (items, concurrency, fn) {
  var failures = [];
  var index = 0;

  var worker = async function () {
    while (index < items.length) {
      var item = items[index++];
      try {
        await fn(item);
      } catch (err) {
        failures.push(item + ": " + (err.message || err));
      }
    }
  };

  var workers = [];
  for (var i = 0; i < Math.min(concurrency, items.length); i++) workers.push(worker());
  await Promise.all(workers);

  return failures;
};

var apply = async function (client, bucket, result, local, concurrency) {
  var s3 = require("@aws-sdk/client-s3");
  var done = 0;

  var failures = await eachLimit(result.upload, concurrency, async function (key) {
    await client.send(new s3.PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: gzipFile(local[key]).body,
      ContentType: "application/json",
      ContentEncoding: "gzip"
    }));

    if (++done % 5000 === 0) console.log("  " + result.table + ": uploaded " + done + "/" + result.upload.length);
  });

  // DeleteObjects accepts up to 1000 keys per call
  for (var i = 0; i < result.delete.length; i += 1000) {
    var batch = result.delete.slice(i, i + 1000);
    var response = await client.send(new s3.DeleteObjectsCommand({
      Bucket: bucket,
      Delete: {
        Objects: batch.map(function (key) {
          return { Key: key };
        }),
        Quiet: true
      }
    }));

    (response.Errors || []).forEach(function (err) {
      failures.push(err.Key + ": " + err.Message);
    });
  }

  return failures;
};

var main = async function () {
  var args = ibpt.parseArgs(process.argv.slice(2));
  var tables = ibpt.parseTables(args.tables, ibpt.allTables);
  var dryRun = !args.apply;
  var bucket = process.env.R2_BUCKET || "ibpt";
  var concurrency = parseInt(args.concurrency, 10) || 32;
  var client = createClient();
  var failed = false;

  console.log((dryRun ? "DRY-RUN" : "APPLY") + " bucket=" + bucket + " tables=" + tables.join(","));

  for (var i = 0; i < tables.length; i++) {
    var table = tables[i];
    console.log(table + ": reading local files and listing the bucket...");
    var local = localFiles(table);

    if (Object.keys(local).length === 0) {
      throw new Error("no local json files for table " + table + ", refusing to publish");
    }

    var remote = await listRemote(client, bucket, table);
    var result = plan(table, local, remote);

    if (args["no-delete"]) result.delete = [];

    console.log(table + ": local=" + Object.keys(local).length + " remote=" + result.remoteCount +
      " upload=" + result.upload.length + " delete=" + result.delete.length + " unchanged=" + result.unchanged);

    if (result.upload.length) console.log("  upload ex: " + result.upload.slice(0, 5).join(", "));
    if (result.delete.length) console.log("  delete ex: " + result.delete.slice(0, 5).join(", "));

    if (result.remoteCount && result.delete.length / result.remoteCount > MASS_DELETE_RATIO && !args["allow-mass-delete"]) {
      throw new Error(table + ": would delete " + result.delete.length + " of " + result.remoteCount +
        " remote files, rerun with --allow-mass-delete if this is expected");
    }

    if (dryRun) continue;

    var failures = await apply(client, bucket, result, local, concurrency);

    if (failures.length) {
      failed = true;
      console.error(table + ": " + failures.length + " failures, ex:\n  " + failures.slice(0, 10).join("\n  "));
    } else {
      console.log(table + ": published");
    }
  }

  if (dryRun) console.log("dry-run: nothing changed, rerun with --apply to publish");
  if (failed) throw new Error("publish finished with failures");
};

module.exports = { plan: plan, isTableKey: isTableKey, gzipFile: gzipFile, listRemote: listRemote, apply: apply };

if (require.main === module) {
  if (fs.existsSync(".env")) require("dotenv").config();

  var finished = false;

  // node exits silently when a promise never settles and nothing else is pending;
  // make that visible instead of looking like a successful run
  process.on("beforeExit", function () {
    if (!finished) {
      console.error("ERROR: exited before finishing (a request never completed), nothing after this point was done");
      process.exit(1);
    }
  });

  main().then(function () {
    finished = true;
  }).catch(function (err) {
    finished = true;
    console.error("ERROR: " + err.message);
    process.exit(1);
  });
}
